### ISSUE TITLE
[ EPIC] Preparations for funding proposal resubmission

### ISSUE THREAD

**Issue by chektien** [singaporetech/democonstruct-research-packet#1]
As the last attempt was rejected at FCP, we will work on resubmitting this.
- [x] identify grant call
- [x] contact ARO for eligibility
- [x] plan for amendments

**Comment by chektien** [comment]
Have identified that MOE TIF may be the next best and have contacted ARO on this awaiting response.

**Comment by chektien** [comment]
the crunch has started for TIF in the new repo at https://github.com/singaporetech/democonstruct-proposal
